import Head from "next/head"
import styles from "../styles/Home.module.css"
import ArticleIndex from "./articles"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Cautious Spork</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ArticleIndex />
		</div>
	)
}
