import { useState } from "react"
import { getData } from "../helper"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import ArticleIndex from "../components/articles"

export default function Home({ articles }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Cautious Spork</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ArticleIndex articles={articles} />
		</div>
	)
}

export const getStaticProps = async () => {
	const articles = await getData()

	return { props: { articles } }
}
